# Generated by Django 4.1.13 on 2026-03-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('Contract_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rent_Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Status', models.CharField(choices=[('ใช้งาน', 'ใช้งาน'), ('หมดอายุ', 'หมดอายุ'), ('ยกเลิก', 'ยกเลิก')], default='ใช้งาน', max_length=20)),
            ],
            options={
                'db_table': 'CONTRACT',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Billing_Date', models.DateField()),
                ('Due_Date', models.DateField()),
                ('Grand_Total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Status', models.CharField(choices=[('รอชำระ', 'รอชำระ'), ('ชำระแล้ว', 'ชำระแล้ว'), ('เกินกำหนด', 'เกินกำหนด')], default='รอชำระ', max_length=20)),
                ('Paid_Date', models.DateField(blank=True, null=True)),
                ('Contract_ID', models.ForeignKey(db_column='Contract_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.contract')),
            ],
            options={
                'db_table': 'INVOICE',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Room_Number', models.CharField(max_length=4, unique=True)),
                ('Building_No', models.CharField(max_length=1)),
                ('Floor', models.CharField(max_length=1)),
                ('Status', models.CharField(choices=[('ว่าง', 'ว่าง'), ('มีผู้เช่า', 'มีผู้เช่า'), ('ซ่อมบำรุง', 'ซ่อมบำรุง')], default='ว่าง', max_length=20)),
            ],
            options={
                'db_table': 'ROOM',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('Tenant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('ID_Card', models.CharField(max_length=13, unique=True)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TENANT',
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('Utility_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_Month', models.DateField()),
                ('Water_Unit_Before', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Water_Unit_After', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Water_Unit_Used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Elec_Unit_Used', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Water_Cost_Unit', models.IntegerField()),
                ('Elec_Cost_Unit', models.IntegerField()),
                ('Water_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Elec_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Invoice_ID', models.OneToOneField(db_column='Invoice_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.invoice')),
                ('Room_ID', models.ForeignKey(db_column='Room_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.room')),
            ],
            options={
                'db_table': 'UTILITY',
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('Monthly_Bill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_Month', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Invoice_ID', models.OneToOneField(db_column='Invoice_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.invoice')),
            ],
            options={
                'db_table': 'MONTHLY_BILL',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('Maintenance_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Problem_Detail', models.CharField(max_length=255)),
                ('Report_Date', models.DateField()),
                ('Status', models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังซ่อม', 'กำลังซ่อม'), ('ซ่อมเสร็จ', 'ซ่อมเสร็จ')], default='รอดำเนินการ', max_length=50)),
                ('Resolved_Date', models.DateField(blank=True, null=True)),
                ('Repair_Cost', models.IntegerField(default=0)),
                ('Invoice_ID', models.ForeignKey(blank=True, db_column='Invoice_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.invoice')),
                ('Room_ID', models.ForeignKey(db_column='Room_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.room')),
            ],
            options={
                'db_table': 'MAINTENANCE',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('Fine_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Reason', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fine_Date', models.DateField()),
                ('Invoice_ID', models.ForeignKey(db_column='Invoice_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.invoice')),
            ],
            options={
                'db_table': 'FINE',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='Room_ID',
            field=models.ForeignKey(db_column='Room_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.room'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Tenant_ID',
            field=models.ForeignKey(db_column='Tenant_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.tenant'),
        ),
    ]
