# Generated by Django 4.1.13 on 2026-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Status_Flag',
            field=models.CharField(choices=[('ปกติ', 'ปกติ'), ('แจ้งย้ายออก', 'แจ้งย้ายออก'), ('จอง', 'จอง'), ('รอทำความสะอาด', 'รอทำความสะอาด')], default='ปกติ', max_length=20),
        ),
    ]
