# Generated by Django 4.1.13 on 2026-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_room_status_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Deposit_Advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='Elec_Cost_Unit',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='contract',
            name='Elec_Meter_Start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='contract',
            name='Water_Cost_Unit',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='contract',
            name='Water_Meter_Start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='Line_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
