# Generated by Django 4.1.13 on 2026-03-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_contract_deposit_advance_contract_elec_cost_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('ID_Card', models.CharField(max_length=13)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Line_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Note', models.CharField(blank=True, max_length=255, null=True)),
                ('Booking_Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(default='รอยืนยัน', max_length=20)),
                ('Room_ID', models.ForeignKey(db_column='Room_ID', on_delete=django.db.models.deletion.PROTECT, to='apartment.room')),
            ],
            options={
                'db_table': 'BOOKING',
            },
        ),
    ]
