# Generated by Django 4.2.29 on 2026-03-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Extended_Due_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Due_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Status',
            field=models.CharField(choices=[('รอชำระ', 'รอชำระ'), ('ชำระแล้ว', 'ชำระแล้ว'), ('เกินกำหนด', 'เกินกำหนด'), ('จ่ายล่าช้า', 'จ่ายล่าช้า'), ('ต่อเวลาชำระ', 'ต่อเวลาชำระ')], default='รอชำระ', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('Contract_ID', 'Billing_Date')},
        ),
    ]
