# Generated by Django 4.2.29 on 2026-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_invoice_extended_due_date_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='Elec_Unit_After',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='utility',
            name='Elec_Unit_Before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='utility',
            name='Elec_Unit_Used',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='utility',
            name='Water_Unit_After',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='utility',
            name='Water_Unit_Before',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='utility',
            name='Water_Unit_Used',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
