# Generated by Django 4.2.29 on 2026-03-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='Email',
            field=models.EmailField(default='none@email.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
