# Generated by Django 4.2.29 on 2026-03-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_tenant_email_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Moveout_Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
