# Generated by Django 4.2.29 on 2026-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_add_moveout_note_to_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('Salary_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Role', models.CharField(choices=[('MANAGER', 'ผู้จัดการ'), ('STAFF', 'พนักงานทั่วไป'), ('SECURITY', 'รักษาความปลอดภัย'), ('CLEANER', 'แม่บ้าน/พนักงานทำความสะอาด'), ('OTHER', 'อื่นๆ')], max_length=20)),
                ('Monthly_Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'EMPLOYEE_SALARY',
            },
        ),
    ]
