# Generated by Django 4.2.29 on 2026-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_add_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='ID_Card',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='เลขบัตรประชาชน'),
        ),
    ]
